CI: exit 1 when ocoman fail

diff --git a/src/build.yml.in b/src/build.yml.in
--- a/src/build.yml.in
+++ b/src/build.yml.in
@@ -495,5 +495,11 @@ jobs:
           xbps-rindex -S --privkey /tmp/private.pem "$NEW_PKGS_DIR"/*.xbps
           rm -f /tmp/private.pem
 
-          BUILDDIR="$NEW_PKGS_DIR" "${GITHUB_WORKSPACE}/extra/ocoman" -p
-          "${GITHUB_WORKSPACE}/extra/ocoman" -a
+          if ! BUILDDIR="$NEW_PKGS_DIR" "${GITHUB_WORKSPACE}/extra/ocoman" -p; then
+            echo "ERROR: Command 'ocoman -p' failed!"
+            exit 1
+          fi
+          if ! "${GITHUB_WORKSPACE}/extra/ocoman" -a; then
+            echo "ERROR: Command 'ocoman -a' failed!"
+            exit 1
+          fi
